### ISSUE TITLE
windows: salt doesn't like it when it can't set file permissions, fails build

### ISSUE THREAD

**Issue by binary1230** [magfest/reggie-formula#13]
both myself and @msg4real are seeing this on windows, even after fixing all the other errors in #12 

```                       
 ID: reggie sideboard configuration
                  Function: file.managed
                      Name: /home/vagrant/reggie-formula/reggie_install/development.ini
                    Result: False
                   Comment: Failed to change mode to 0644
                   Started: 00:53:13.822270
                  Duration: 64.338 ms
                   Changes:
                            ----------
                            diff:
                                New file
```

my working theory is:
chmod 0644 on vboxfs (which shares windows file system into linux) allows you to set the file permission BUT won't actually change it.   when you do this, the file permissions stay the same (0755), so I'm guessing that is what it means by "failed to change mode"

I can repro this manually like this:

```bash
# file has 777 permission
(env) vagrant@localhost:~/reggie-formula/reggie_install$ stat -c '%a %n' development.ini
777 development.ini

# change to 644 permission
(env) vagrant@localhost:~/reggie-formula/reggie_install$ chmod 0644 development.ini
# no error, but.....

# permission should have changed, didn't
(env) vagrant@localhost:~/reggie-formula/reggie_install$ stat -c '%a %n' development.ini
777 development.ini
```

So I think we'll probably just need to make the chmod stuff either not verify or not try and change when we're under windows.
